
title: Minesweeper
description: >- # this means to ignore newlines until "baseurl:"

baseurl: Minesweeper
domain: redisskacat.github.io
url: https://redisskacat.github.io
github:
  is_user_page: redisskaCAT
  is_project_page: redisskaCAT/Minesweeper
  repository_url: https://github.com/redisskaCAT/Minesweeper
  owner_url: https://github.com/redisskaCAT
  
markdown: kramdown
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
